package com.dawes.modelo;
// Generated 25-ene-2018 10:02:38 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Actividad generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "actividad", catalog = "gamitour")
public class Actividad implements java.io.Serializable {

	private Integer idactividad;
	private String nombre;
	private Date fechainicio;
	private Date fechafin;
	private String ubicacion;
	private Integer numparticipantes;
	private Float precio;
	private String imagen;
	private Integer puntos;
	private Set<ClienteHasActividad> clienteHasActividads = new HashSet<ClienteHasActividad>(0);

	public Actividad() {
	}

	public Actividad(String nombre, Date fechainicio, Date fechafin, String ubicacion, Integer numparticipantes,
			Float precio, String imagen, Integer puntos, Set<ClienteHasActividad> clienteHasActividads) {
		this.nombre = nombre;
		this.fechainicio = fechainicio;
		this.fechafin = fechafin;
		this.ubicacion = ubicacion;
		this.numparticipantes = numparticipantes;
		this.precio = precio;
		this.imagen = imagen;
		this.puntos = puntos;
		this.clienteHasActividads = clienteHasActividads;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idactividad", unique = true, nullable = false)
	public Integer getIdactividad() {
		return this.idactividad;
	}

	public void setIdactividad(Integer idactividad) {
		this.idactividad = idactividad;
	}

	@Column(name = "nombre", length = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechainicio", length = 10)
	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechafin", length = 10)
	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	@Column(name = "ubicacion", length = 60)
	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	@Column(name = "numparticipantes")
	public Integer getNumparticipantes() {
		return this.numparticipantes;
	}

	public void setNumparticipantes(Integer numparticipantes) {
		this.numparticipantes = numparticipantes;
	}

	@Column(name = "precio", precision = 12, scale = 0)
	public Float getPrecio() {
		return this.precio;
	}

	public void setPrecio(Float precio) {
		this.precio = precio;
	}

	@Column(name = "imagen", length = 60)
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Column(name = "puntos")
	public Integer getPuntos() {
		return this.puntos;
	}

	public void setPuntos(Integer puntos) {
		this.puntos = puntos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actividad")
	public Set<ClienteHasActividad> getClienteHasActividads() {
		return this.clienteHasActividads;
	}

	public void setClienteHasActividads(Set<ClienteHasActividad> clienteHasActividads) {
		this.clienteHasActividads = clienteHasActividads;
	}

}
