package com.dawes.modelo;
// Generated 25-ene-2018 10:02:38 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClienteHasActividad generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "cliente_has_actividad", catalog = "gamitour")
public class ClienteHasActividad implements java.io.Serializable {

	private Integer clienteHasActividadId;
	private Actividad actividad;
	private Cliente cliente;
	private Integer numparticipantesact;
	private Date fechaInscripcion;

	public ClienteHasActividad() {
	}

	public ClienteHasActividad(Actividad actividad, Cliente cliente) {
		this.actividad = actividad;
		this.cliente = cliente;
	}

	public ClienteHasActividad(Actividad actividad, Cliente cliente, Integer numparticipantesact,
			Date fechaInscripcion) {
		this.actividad = actividad;
		this.cliente = cliente;
		this.numparticipantesact = numparticipantesact;
		this.fechaInscripcion = fechaInscripcion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cliente_has_actividad_id", unique = true, nullable = false)
	public Integer getClienteHasActividadId() {
		return this.clienteHasActividadId;
	}

	public void setClienteHasActividadId(Integer clienteHasActividadId) {
		this.clienteHasActividadId = clienteHasActividadId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "actividad_idactividad", nullable = false)
	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cliente_idcliente", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Column(name = "numparticipantesact")
	public Integer getNumparticipantesact() {
		return this.numparticipantesact;
	}

	public void setNumparticipantesact(Integer numparticipantesact) {
		this.numparticipantesact = numparticipantesact;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaInscripción", length = 10)
	public Date getFechaInscripcion() {
		return this.fechaInscripcion;
	}

	public void setFechaInscripcion(Date fechaInscripcion) {
		this.fechaInscripcion = fechaInscripcion;
	}

}
