package com.dawes.modelo;
// Generated 25-ene-2018 10:02:38 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Itinerario generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "itinerario", catalog = "gamitour")
public class Itinerario implements java.io.Serializable {

	private Integer iditinerario;
	private String nombre;
	private String categoria;
	private String duracion;
	private String ubicacion;
	private Set<Parada> paradas = new HashSet<Parada>(0);

	public Itinerario() {
	}

	public Itinerario(String nombre, String categoria, String duracion, String ubicacion, Set<Parada> paradas) {
		this.nombre = nombre;
		this.categoria = categoria;
		this.duracion = duracion;
		this.ubicacion = ubicacion;
		this.paradas = paradas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "iditinerario", unique = true, nullable = false)
	public Integer getIditinerario() {
		return this.iditinerario;
	}

	public void setIditinerario(Integer iditinerario) {
		this.iditinerario = iditinerario;
	}

	@Column(name = "nombre", length = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "categoria", length = 45)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	@Column(name = "duracion", length = 15)
	public String getDuracion() {
		return this.duracion;
	}

	public void setDuracion(String duracion) {
		this.duracion = duracion;
	}

	@Column(name = "ubicacion", length = 45)
	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "itinerario")
	public Set<Parada> getParadas() {
		return this.paradas;
	}

	public void setParadas(Set<Parada> paradas) {
		this.paradas = paradas;
	}

}
