package com.dawes.modelo;
// Generated 25-ene-2018 10:02:38 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Multimedia generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "multimedia", catalog = "gamitour")
public class Multimedia implements java.io.Serializable {

	private Integer idmultimedia;
	private Cliente cliente;
	private PruebaDeportiva pruebaDeportiva;
	private Date fecha;
	private String comentario;
	private String imagen;
	private String video;
	private Integer puntosacumulados;
	private Set<Comentario> comentarios = new HashSet<Comentario>(0);
	private Set<Voto> votos = new HashSet<Voto>(0);

	public Multimedia() {
	}

	public Multimedia(Cliente cliente, PruebaDeportiva pruebaDeportiva) {
		this.cliente = cliente;
		this.pruebaDeportiva = pruebaDeportiva;
	}

	public Multimedia(Cliente cliente, PruebaDeportiva pruebaDeportiva, Date fecha, String comentario, String imagen,
			String video, Integer puntosacumulados, Set<Comentario> comentarios, Set<Voto> votos) {
		this.cliente = cliente;
		this.pruebaDeportiva = pruebaDeportiva;
		this.fecha = fecha;
		this.comentario = comentario;
		this.imagen = imagen;
		this.video = video;
		this.puntosacumulados = puntosacumulados;
		this.comentarios = comentarios;
		this.votos = votos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idmultimedia", unique = true, nullable = false)
	public Integer getIdmultimedia() {
		return this.idmultimedia;
	}

	public void setIdmultimedia(Integer idmultimedia) {
		this.idmultimedia = idmultimedia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cliente_idcliente", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pruebaDeportiva_idpruebadeportiva", nullable = false)
	public PruebaDeportiva getPruebaDeportiva() {
		return this.pruebaDeportiva;
	}

	public void setPruebaDeportiva(PruebaDeportiva pruebaDeportiva) {
		this.pruebaDeportiva = pruebaDeportiva;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "comentario", length = 60)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Column(name = "imagen", length = 60)
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Column(name = "video", length = 60)
	public String getVideo() {
		return this.video;
	}

	public void setVideo(String video) {
		this.video = video;
	}

	@Column(name = "puntosacumulados")
	public Integer getPuntosacumulados() {
		return this.puntosacumulados;
	}

	public void setPuntosacumulados(Integer puntosacumulados) {
		this.puntosacumulados = puntosacumulados;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "multimedia")
	public Set<Comentario> getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(Set<Comentario> comentarios) {
		this.comentarios = comentarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "multimedia")
	public Set<Voto> getVotos() {
		return this.votos;
	}

	public void setVotos(Set<Voto> votos) {
		this.votos = votos;
	}

}
