package com.dawes.modelo;
// Generated 25-ene-2018 10:02:38 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Premio generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "premio", catalog = "gamitour")
public class Premio implements java.io.Serializable {

	private Integer idpremio;
	private Cliente cliente;
	private String nombre;
	private String descripcion;
	private String imagen;
	private Date fechaactivacion;
	private Date fechaconsumo;
	private Integer puntos;

	public Premio() {
	}

	public Premio(Cliente cliente) {
		this.cliente = cliente;
	}

	public Premio(Cliente cliente, String nombre, String descripcion, String imagen, Date fechaactivacion,
			Date fechaconsumo, Integer puntos) {
		this.cliente = cliente;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.imagen = imagen;
		this.fechaactivacion = fechaactivacion;
		this.fechaconsumo = fechaconsumo;
		this.puntos = puntos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idpremio", unique = true, nullable = false)
	public Integer getIdpremio() {
		return this.idpremio;
	}

	public void setIdpremio(Integer idpremio) {
		this.idpremio = idpremio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cliente_idcliente", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Column(name = "nombre", length = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "imagen", length = 45)
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaactivacion", length = 10)
	public Date getFechaactivacion() {
		return this.fechaactivacion;
	}

	public void setFechaactivacion(Date fechaactivacion) {
		this.fechaactivacion = fechaactivacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaconsumo", length = 10)
	public Date getFechaconsumo() {
		return this.fechaconsumo;
	}

	public void setFechaconsumo(Date fechaconsumo) {
		this.fechaconsumo = fechaconsumo;
	}

	@Column(name = "puntos")
	public Integer getPuntos() {
		return this.puntos;
	}

	public void setPuntos(Integer puntos) {
		this.puntos = puntos;
	}

}
